package token

const (
  LPAREN = "("
  RPAREN = ")"
  LVECT = "["
  RVECT = "]"

  IF = "if"
  LET = "let"
  LET_STAR = "let*"
  LETREC = "letrec"
  DEFINE = "define"
  IMPORT = "import"
  BEGIN = "begin"
  COND = "cond"
  ELSE = "else"
  CASE = "case"
  UNLESS = "unless"
  WHEN = "when"
  TRUE = "#t"
  FALSE = "#f"
  LAMBDA = "lambda"
  TUPLE = "tuple"
  IDENT = "ident"
  BIND = "bind"
  BINDS = "binds"
  SET = "set!"
  DISPLAY = "display"
  QUOTE = "quote"
  QUASIQUOTE = "quasiquote"
  CALL = "call"
  NOTATION = "notation"
  COMMA = ","

  CHAR = "char"
  STRING = "string"
  INT = "int"
  FLOAT = "float"
  PROC = "proc"
  BOOL = "bool"
  LIST = "list"
)
